version: "3"
networks:
  laravel1:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx1
    ports:
      - "8082:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel1
  mysql: 
    image: mysql:8
    container_name: laravel_mysql1
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER : root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: emart     
      #MYSQL_SERVICE_NAME : mysql
    networks:
      - laravel1
  
  phpmyadmin:

    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8083:80"
    environment:
      MYSQL_ROOT_PASSWORD: root #(Required) set the password for the root superuser account.
      PMA_HOST: mysql   # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: root # use the root password to login on startup.
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - laravel1
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php1
    ports: 
      - "9000:9000"
    volumes: 
      - "./:/var/www/html"
    networks:
      - laravel1